# Generated by Django 3.1.6 on 2021-04-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('picture_id', models.AutoField(primary_key=True, serialize=False)),
                ('picture', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
    ]
