# Generated by Django 3.1.6 on 2021-04-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '料理画像',
                'verbose_name_plural': '料理画像',
            },
        ),
    ]
