# Generated by Django 3.1.6 on 2021-04-18 16:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': '料理画像', 'verbose_name_plural': '料理画像'},
        ),
        migrations.RemoveField(
            model_name='image',
            name='picture_id',
        ),
        migrations.AddField(
            model_name='image',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
