# Generated by Django 3.1.6 on 2021-04-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_auto_20210419_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
