# Generated by Django 3.1.6 on 2021-04-19 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_auto_20210419_0130'),
        ('album', '0003_auto_20210419_0125'),
    ]

    operations = [
    ]
