# Generated by Django 3.1.6 on 2021-03-30 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('food_CD', models.AutoField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('unit', models.CharField(max_length=5)),
                ('expiration_date', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_CD', models.AutoField(primary_key=True, serialize=False)),
                ('menu_name', models.CharField(max_length=30)),
                ('popularity', models.IntegerField()),
                ('menu_price', models.IntegerField()),
                ('group', models.CharField(max_length=3)),
                ('share', models.CharField(max_length=3)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shopping_list',
            fields=[
                ('shopping_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('timing', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('memo', models.CharField(max_length=100)),
                ('buy_date', models.DateTimeField(auto_now_add=True)),
                ('buy_end', models.CharField(max_length=10)),
                ('food_CD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodmanager.food')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Use_food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_CD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodmanager.food')),
                ('menu_CD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodmanager.menu')),
                ('quantity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodmanager.shopping_list')),
            ],
        ),
        migrations.CreateModel(
            name='Stock_history',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('in_out', models.CharField(max_length=10)),
                ('buy_count', models.IntegerField()),
                ('in_date', models.DateField()),
                ('use_date', models.DateField()),
                ('use_qntty', models.IntegerField()),
                ('expiration', models.IntegerField()),
                ('food_CD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodmanager.food')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_qntty', models.IntegerField()),
                ('food_CD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodmanager.food')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('timing', models.CharField(max_length=20)),
                ('menu_CD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodmanager.menu')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how_to_make', models.CharField(max_length=300)),
                ('menu_CD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodmanager.menu')),
            ],
        ),
    ]
