# Generated by Django 3.1.6 on 2021-04-21 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('food_CD', models.AutoField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('unit', models.CharField(max_length=5)),
                ('expiration_date', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': '食材',
                'verbose_name_plural': '食材',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '料理画像',
                'verbose_name_plural': '料理画像',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_CD', models.AutoField(primary_key=True, serialize=False)),
                ('menu_name', models.CharField(max_length=30)),
                ('popularity', models.IntegerField()),
                ('menu_price', models.IntegerField()),
                ('group', models.CharField(max_length=3)),
                ('share', models.CharField(max_length=3)),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodmanager.image')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'メニュー',
                'verbose_name_plural': 'メニュー',
            },
        ),
        migrations.CreateModel(
            name='Use_food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_quantity', models.FloatField(default=1.0)),
                ('food_CD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodmanager.food')),
                ('menu_CD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodmanager.menu')),
            ],
            options={
                'verbose_name': '使用食材',
                'verbose_name_plural': '使用食材',
            },
        ),
        migrations.CreateModel(
            name='Stock_history',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('in_out', models.CharField(max_length=10)),
                ('buy_count', models.IntegerField()),
                ('in_date', models.DateField(blank=True, null=True)),
                ('use_date', models.DateField(blank=True, null=True)),
                ('use_qntty', models.IntegerField()),
                ('expiration', models.IntegerField()),
                ('food_CD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodmanager.food')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '在庫履歴',
                'verbose_name_plural': '在庫履歴',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_qntty', models.IntegerField()),
                ('food_CD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodmanager.food')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '在庫',
                'verbose_name_plural': '在庫',
            },
        ),
        migrations.CreateModel(
            name='Shopping_list',
            fields=[
                ('shopping_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('timing', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('memo', models.CharField(blank=True, max_length=100, null=True)),
                ('buy_date', models.DateTimeField(auto_now_add=True)),
                ('buy_end', models.CharField(max_length=10)),
                ('food_CD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodmanager.food')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '買い物リスト',
                'verbose_name_plural': '買い物リスト',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('timing', models.CharField(max_length=20)),
                ('menu_CD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodmanager.menu')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'スケジュール',
                'verbose_name_plural': 'スケジュール',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how_to_make', models.CharField(max_length=300)),
                ('menu_CD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodmanager.menu')),
            ],
            options={
                'verbose_name': 'レシピ',
                'verbose_name_plural': 'レシピ',
            },
        ),
    ]
