# Generated by Django 3.1.6 on 2021-03-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping_list',
            name='memo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
