# Generated by Django 3.1.6 on 2021-03-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmanager', '0002_auto_20210330_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping_list',
            name='memo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
