# Generated by Django 3.1.6 on 2021-03-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmanager', '0003_auto_20210330_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_history',
            name='use_date',
            field=models.DateField(null=True),
        ),
    ]
