# Generated by Django 3.1.6 on 2021-03-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmanager', '0004_auto_20210330_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_history',
            name='in_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock_history',
            name='use_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
