# Generated by Django 3.1.6 on 2021-03-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmanager', '0005_auto_20210330_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='use_food',
            name='quantity',
        ),
        migrations.AddField(
            model_name='use_food',
            name='use_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
