# Generated by Django 3.1.6 on 2021-04-18 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodmanager', '0006_auto_20210330_2255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'verbose_name': '食材', 'verbose_name_plural': '食材'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'メニュー', 'verbose_name_plural': 'メニュー'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'レシピ', 'verbose_name_plural': 'レシピ'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'スケジュール', 'verbose_name_plural': 'スケジュール'},
        ),
        migrations.AlterModelOptions(
            name='shopping_list',
            options={'verbose_name': '買い物リスト', 'verbose_name_plural': '買い物リスト'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': '在庫', 'verbose_name_plural': '在庫'},
        ),
        migrations.AlterModelOptions(
            name='stock_history',
            options={'verbose_name': '在庫履歴', 'verbose_name_plural': '在庫履歴'},
        ),
        migrations.AlterModelOptions(
            name='use_food',
            options={'verbose_name': '使用食材', 'verbose_name_plural': '使用食材'},
        ),
    ]
