# Generated by Django 3.1.6 on 2021-04-18 16:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_auto_20210419_0120'),
        ('foodmanager', '0007_auto_20210418_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='picture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album.image'),
            
        ),
    ]
